version: 2.1
orbs:
  github-release: h-matsuo/github-release@0.1.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
      - image: circleci/golang:1.8
    working_directory: ~/build
    executor: github-release/default
    steps:
      - checkout
      - run:
          name: Compile and create Jars
          command: |
            CIRCLE_BUILD_NUM=$(($CIRCLE_BUILD_NUM + 303))
            echo ${CIRCLE_BUILD_NUM}
            mvn clean install
            mkdir ~/build/dev
            cp ~/build/RedProtect-Sponge-8/target/*.jar ~/build/dev/
            rm ~/build/dev/*DONT-DOWNLOAD*
            FILE=find ./build/dev/ -name "*.jar" -printf "%f"
            echo f${FILE}
            PROJECT_VERSION=${FILE%%%-*}
      - store_artifacts:
          name: Dev Build
          path: ~/build/dev/
      - github-release/create:
          tag: v${PROJECT_VERSION}
          title: ${CIRCLE_PROJECT_REPONAME} v${PROJECT_VERSION} build ${CIRCLE_BUILD_NUM}
          description: ${CIRCLE_PROJECT_REPONAME} v${PROJECT_VERSION} build ${CIRCLE_BUILD_NUM}
          file-path: ~/build/dev/
          pre-release: true